import React from 'react';

interface LogicVisualizerProps {
  diagramCode: string;
}

const SyntaxHighlighter: React.FC<{ code: string }> = ({ code }) => {
  const processLine = (line: string, index: number) => {
    // 1. Escape HTML characters to prevent injection and render text correctly
    let safeLine = line
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    // 2. Identify Comments (starts with %%)
    if (safeLine.trim().startsWith("%%")) {
      return (
        <div key={index} className="text-stone-400 italic">
          {line}
        </div>
      );
    }

    // 3. Highlight Logic using Regex replacements
    // Note: Order matters to avoid replacing inside existing tags.
    // We are replacing raw text with HTML strings, then rendering safely.

    // Keywords
    safeLine = safeLine.replace(
      /\b(graph|flowchart|subgraph|end|classDef|style|click)\b/g,
      '<span class="text-violet-700 font-bold">$1</span>'
    );

    // Directions
    safeLine = safeLine.replace(
      /\b(TB|TD|BT|RL|LR)\b/g,
      '<span class="text-violet-500 font-semibold">$1</span>'
    );

    // Arrows (e.g., -->, ---, -.->, ==>)
    // Regex must account for the escaped &gt; for >
    safeLine = safeLine.replace(
      /(-{1,3}&gt;?|\.{1,3}&gt;?|={1,3}&gt;?)/g,
      '<span class="text-amber-600 font-bold">$1</span>'
    );

    // Brackets and Parentheses (Node delimiters)
    safeLine = safeLine.replace(
      /([\[\]\(\)\{\}])/g,
      '<span class="text-blue-600 font-bold">$1</span>'
    );
    
    // Strings (quoted text)
    safeLine = safeLine.replace(
      /("[^"]*")/g,
      '<span class="text-emerald-600">$1</span>'
    );

    // Pipe labels e.g. |Yes|
    safeLine = safeLine.replace(
      /(\|[^|]+\|)/g,
      '<span class="text-stone-500 italic">$1</span>'
    );

    return (
      <div 
        key={index} 
        dangerouslySetInnerHTML={{ __html: safeLine }} 
        className="min-h-[1.2em]" 
      />
    );
  };

  return (
    <div className="font-mono text-sm leading-relaxed text-stone-700 whitespace-pre-wrap">
      {code.split('\n').map((line, i) => processLine(line, i))}
    </div>
  );
};

export const LogicVisualizer: React.FC<LogicVisualizerProps> = ({ diagramCode }) => {
  if (!diagramCode) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-stone-400 p-8 text-center border-2 border-dashed border-stone-200 rounded-2xl bg-stone-50/50">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mb-4 opacity-40 text-stone-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
        </svg>
        <p className="text-lg font-medium text-stone-500">No Logic Diagram Yet</p>
        <p className="text-sm mt-2 text-stone-400">Interact with Unnamed AI to generate a structural map of your problem.</p>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-white rounded-2xl border border-stone-200 shadow-sm overflow-hidden">
      <div className="bg-stone-50 px-5 py-3 border-b border-stone-200 flex items-center justify-between">
        <span className="text-xs font-bold text-violet-600 uppercase tracking-widest">Logic Blueprint</span>
        <div className="flex space-x-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-stone-300"></div>
          <div className="w-2.5 h-2.5 rounded-full bg-stone-300"></div>
        </div>
      </div>
      <div className="flex-1 p-6 overflow-auto bg-white">
        <SyntaxHighlighter code={diagramCode} />
      </div>
      <div className="bg-stone-50 px-5 py-2 border-t border-stone-200 text-right">
         <span className="text-[10px] text-stone-400 uppercase tracking-wide">Generated by Unnamed</span>
      </div>
    </div>
  );
};